{% set name = "ldas-tools-framecpp" %}
{% set version = "3.0.0" %}

# dependency versions
{% set ldas_tools_al_version = "2.6.7" %}
{% set ldas_tools_cmake_version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: cf1e1d30eff8c952796e8ceac90267460f3d7541ea95d72dd9854dccdacf1d1c
  patches:
    # disable building static libraries
    - no-static.patch
    # backport https://git.ligo.org/computing/ldastools/LDAS_Tools/-/merge_requests/143
    - fracfg-version9.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-framecpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - gmock
    - gtest
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - openssl
    - zlib
    - zstd
  run:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    # framecpp_sample creates Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_sample
    - framecpp_checksum --verbose --checksum-file --checksum-frame --checksum-structure Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_compressor --compression-level 9 --output compressed.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_channel --channel Z0:RAMPED_INT_2U_1 Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_objects --silent Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_toc Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_fix_metadata --output fixed.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_fracfg --channels Z0:RAMPED_INT_2U_1 --output fracfg.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_toc fracfg.gwf
    - framecpp_transform --help
    - framecpp_verify --verbose Z-ilwd_test_frame-600000000-1.gwf
    - pkg-config --print-errors --exact-version {{ version }} framecpp  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp_common  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecppc  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp3  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp4  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp6  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp7  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp8  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} framecpp9  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
  doc_url: https://computing.docs.ligo.org/ldastools/LDAS_Tools/ldas-tools-framecpp/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools libframecpp toolkit runtime files
  description: |
    This provides the runtime libraries for the framecpp library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
