{% set name = "ldas-tools-framecpp" %}
{% set version = "2.7.1" %}
{% set sha256 = "88d9f1507c3591544ffb050cab7b68c052e85ff276c3128dc918d3cb10073830" %}

{% set ldas_tools_al_version = "2.6.3" %}
{% set ldas_tools_cmake_version = "1.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-framecpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }},<1.2.0
    - openssl
    - zlib
  run:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    # framecpp_sample creates Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_sample
    - framecpp_checksum --verbose --checksum-file --checksum-frame --checksum-structure Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_compressor --compression-level 9 --output compressed.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_channel --channel Z0:RAMPED_INT_2U_1 Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_objects --silent Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_toc Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_fix_metadata --output fixed.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_fracfg --channels Z0:RAMPED_INT_2U_1 --output fracfg.gwf Z-ilwd_test_frame-600000000-1.gwf
    - framecpp_dump_toc fracfg.gwf
    - framecpp_transform --help
    - framecpp_verify --verbose Z-ilwd_test_frame-600000000-1.gwf
    - pkg-config --print-errors --modversion framecpp  # [unix]
    - pkg-config --print-errors --modversion framecpp_common  # [unix]
    - pkg-config --print-errors --modversion framecppc  # [unix]
    - pkg-config --print-errors --modversion framecpp3  # [unix]
    - pkg-config --print-errors --modversion framecpp4  # [unix]
    - pkg-config --print-errors --modversion framecpp6  # [unix]
    - pkg-config --print-errors --modversion framecpp7  # [unix]
    - pkg-config --print-errors --modversion framecpp8  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools libframecpp toolkit runtime files
  description: |
    This provides the runtime libraries for the framecpp library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
