{% set name = "ldas-tools-framecpp" %}
{% set version = "2.6.3" %}
{% set sha256 = "066a0f5a2d2bbdd04ee5247b9308668d935cd87b1dbf512c2565a7e4e3e4a540" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - boost-cpp
    - openssl
    - ldas-tools-al >=2.6.0
  run:
    - boost-cpp
    - openssl
    - ldas-tools-al >=2.6.0

test:
  commands:
    - framecpp_checksum --help
    - framecpp_compressor --help
    - framecpp_dump_channel --help
    - framecpp_dump_objects --help
    - framecpp_dump_toc --help
    - framecpp_fix_metadata --help
    - framecpp_query --help
    - framecpp_sample --help
    - framecpp_transform --help
    - framecpp_verify --help

about:
  home: https://ldastools.docs.ligo.org/LDAS_Tools/Beta/doc/ldas-tools-framecpp/framecpp/html/
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  doc_url: https://ldastools.docs.ligo.org/LDAS_Tools/Beta/doc/ldas-tools-framecpp/framecpp/html/
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools libframecpp toolkit runtime files
  description: |
    This provides the runtime libraries for the framecpp library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
