travis:
  secure:
    BINSTAR_TOKEN: mVslj8zRKyuUU4k+ixK0fKUAimvc0zguEVyhwg4H1pYX0ykKxyUOYMAG4oEt/R4wT/HHB9vMTNpItUXo0rc2E0KTcldIArwc5WWxlj1JfBfSlMqzJcTgDdD3B374fgsL6wsDHRQr6fpk0ZZpfiSwfOxnao+OJaBOm1GwXMaoZoLqibC9UO1V/ua/m/SxyCH4aBJRgOAmNnavv2zibqY3hNOKvfiBnLMAuKf/SR/czCjU/W/YTlS6olUOse+uQXZC8+0GboxY44PyQRFeJaIRbcWMAaksoGGi/uW4hOe63p63EQrlAAVN9pm5n4pXxDHbtGUNnoJiegLr4CByRhCX54gdjCmn0n5EdU/Nx3LcDEq7VYqwCHMCMwNGokYYxNJKqa1uoVpsihz0wPKpq6EoBkNkUHIRPq9icuUbrO6xHZlXrJ3jKqtrCN010DQyPrpNCQVgGS69N2SbPZIiJecx9FNfKR2DorMWphid0kZ3PzyZY9UQcdh7x1CkVwb8uPRlLAc6+Jo9nLvaejl5KJBYp7KHUYMqM+RziWNfs07Dw3YBBGMKOgpVp+OEf9biVrAoEy7tSlF1n9Sb1e54JP3TUDGI22PViz4NeLeDfwL//80YDorm05bOxYGCktAYCVglw0/Ic4/lDA4IHmFF351uWhOuGvY+1nsudOcASB5yX2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
